language: python
matrix:
  include:
    - python: 3.0
      env: TOXENV=py30
    - python: 3.1
      env: TOXENV=py31
    - python: 3.2
      env: TOXENV=py32
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
install:
  - pip install tox
script:
  - tox